// "use client";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import Navbar from "@/components/Navbar"
import './globals.css'
import Footer from '@/components/Footer';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>

        <Navbar/>
        {children}
        <Footer/>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
